version: "3.8"

services:

  portal:
    build: ../portal/api
    ports:
      - "9090:9090"
    depends_on:
      - mongo
      - sql

  mongo:
    build:
      context: ../portal/api/persistence
      dockerfile: mongo.DockerFile
    ports:
      - "27017:27017"

  sql:
    build:
      context: ../portal/api/persistence
      dockerfile: sql.DockerFile
